name: Eslint check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
    run-eslint:
      name: Run eslint
      runs-on: ubuntu-latest

      steps:
        - name: Check out Git repository
          uses: actions/checkout@v2

        - name: Read .nvmrc
          run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
          id: nvm

        - name: Set up Node.js
          uses: actions/setup-node@v1
          with:
            node-version: "${{ steps.nvm.outputs.NVMRC }}"

        - name: Install Node.js dependencies
          run: npm ci

        - name: Linter check
          run: npx eslint ./src